/*
Url Manager Service

The URL Manager service provides a set of APIs for managing URL rewrites within your application. URL rewriting is a technique used to modify the appearance or structure of URLs while maintaining the functionality and accessibility of the underlying resources.  The URL Manager service offers various operations to create, retrieve, update, and delete URL rewrite configurations. These configurations allow you to define rules that map incoming URLs to different paths or destinations based on specific criteria. By using URL rewriting, you can enhance the user experience, improve SEO (Search Engine Optimization), and manage complex URL structures effectively.  To get started with the URL Manager service, you need to integrate the provided Proto API into your application. The API supports various programming languages and frameworks, making it easy to incorporate URL rewriting functionality into your existing codebase.  Once integrated, you can utilize the different API methods to create, manage, and query URL rewrite configurations based on your application's requirements.  Refer to the API documentation for detailed information on the request and response formats, authentication requirements, and example usage of each API method.

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package urlmanager

import (
	"encoding/json"
)

// checks if the GetUrlRewriteRequestCompoundIdentifier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUrlRewriteRequestCompoundIdentifier{}

// GetUrlRewriteRequestCompoundIdentifier struct for GetUrlRewriteRequestCompoundIdentifier
type GetUrlRewriteRequestCompoundIdentifier struct {
	Context *string `json:"context,omitempty"`
	RequestPath *string `json:"requestPath,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetUrlRewriteRequestCompoundIdentifier GetUrlRewriteRequestCompoundIdentifier

// NewGetUrlRewriteRequestCompoundIdentifier instantiates a new GetUrlRewriteRequestCompoundIdentifier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUrlRewriteRequestCompoundIdentifier() *GetUrlRewriteRequestCompoundIdentifier {
	this := GetUrlRewriteRequestCompoundIdentifier{}
	return &this
}

// NewGetUrlRewriteRequestCompoundIdentifierWithDefaults instantiates a new GetUrlRewriteRequestCompoundIdentifier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUrlRewriteRequestCompoundIdentifierWithDefaults() *GetUrlRewriteRequestCompoundIdentifier {
	this := GetUrlRewriteRequestCompoundIdentifier{}
	return &this
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *GetUrlRewriteRequestCompoundIdentifier) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUrlRewriteRequestCompoundIdentifier) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// &#39;Has&#39;Context returns a boolean if a field has been set.
func (o *GetUrlRewriteRequestCompoundIdentifier) &#39;Has&#39;Context() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *GetUrlRewriteRequestCompoundIdentifier) SetContext(v string) {
	o.Context = &v
}

// GetRequestPath returns the RequestPath field value if set, zero value otherwise.
func (o *GetUrlRewriteRequestCompoundIdentifier) GetRequestPath() string {
	if o == nil || IsNil(o.RequestPath) {
		var ret string
		return ret
	}
	return *o.RequestPath
}

// GetRequestPathOk returns a tuple with the RequestPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUrlRewriteRequestCompoundIdentifier) GetRequestPathOk() (*string, bool) {
	if o == nil || IsNil(o.RequestPath) {
		return nil, false
	}
	return o.RequestPath, true
}

// &#39;Has&#39;RequestPath returns a boolean if a field has been set.
func (o *GetUrlRewriteRequestCompoundIdentifier) &#39;Has&#39;RequestPath() bool {
	if o != nil && !IsNil(o.RequestPath) {
		return true
	}

	return false
}

// SetRequestPath gets a reference to the given string and assigns it to the RequestPath field.
func (o *GetUrlRewriteRequestCompoundIdentifier) SetRequestPath(v string) {
	o.RequestPath = &v
}

func (o GetUrlRewriteRequestCompoundIdentifier) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUrlRewriteRequestCompoundIdentifier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.RequestPath) {
		toSerialize["requestPath"] = o.RequestPath
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetUrlRewriteRequestCompoundIdentifier) UnmarshalJSON(data []byte) (err error) {
	varGetUrlRewriteRequestCompoundIdentifier := _GetUrlRewriteRequestCompoundIdentifier{}

	err = json.Unmarshal(data, &varGetUrlRewriteRequestCompoundIdentifier)

	if err != nil {
		return err
	}

	*o = GetUrlRewriteRequestCompoundIdentifier(varGetUrlRewriteRequestCompoundIdentifier)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "context")
		delete(additionalProperties, "requestPath")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *GetUrlRewriteRequestCompoundIdentifier) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *GetUrlRewriteRequestCompoundIdentifier) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableGetUrlRewriteRequestCompoundIdentifier struct {
	value *GetUrlRewriteRequestCompoundIdentifier
	isSet bool
}

func (v NullableGetUrlRewriteRequestCompoundIdentifier) Get() *GetUrlRewriteRequestCompoundIdentifier {
	return v.value
}

func (v *NullableGetUrlRewriteRequestCompoundIdentifier) Set(val *GetUrlRewriteRequestCompoundIdentifier) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUrlRewriteRequestCompoundIdentifier) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUrlRewriteRequestCompoundIdentifier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUrlRewriteRequestCompoundIdentifier(val *GetUrlRewriteRequestCompoundIdentifier) *NullableGetUrlRewriteRequestCompoundIdentifier {
	return &NullableGetUrlRewriteRequestCompoundIdentifier{value: val, isSet: true}
}

func (v NullableGetUrlRewriteRequestCompoundIdentifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUrlRewriteRequestCompoundIdentifier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


