/*
Url Manager Service

The URL Manager service provides a set of APIs for managing URL rewrites within your application. URL rewriting is a technique used to modify the appearance or structure of URLs while maintaining the functionality and accessibility of the underlying resources.  The URL Manager service offers various operations to create, retrieve, update, and delete URL rewrite configurations. These configurations allow you to define rules that map incoming URLs to different paths or destinations based on specific criteria. By using URL rewriting, you can enhance the user experience, improve SEO (Search Engine Optimization), and manage complex URL structures effectively.  To get started with the URL Manager service, you need to integrate the provided Proto API into your application. The API supports various programming languages and frameworks, making it easy to incorporate URL rewriting functionality into your existing codebase.  Once integrated, you can utilize the different API methods to create, manage, and query URL rewrite configurations based on your application's requirements.  Refer to the API documentation for detailed information on the request and response formats, authentication requirements, and example usage of each API method.

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package urlmanager

import (
	"encoding/json"
)

// checks if the UrlmanagerCreateUrlRewriteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UrlmanagerCreateUrlRewriteRequest{}

// UrlmanagerCreateUrlRewriteRequest struct for UrlmanagerCreateUrlRewriteRequest
type UrlmanagerCreateUrlRewriteRequest struct {
	// Required.
	TenantId *string `json:"tenantId,omitempty"`
	// Required.
	Context *string `json:"context,omitempty"`
	// Required.
	RequestPath *string `json:"requestPath,omitempty"`
	// Required.
	TargetPath           *string                 `json:"targetPath,omitempty"`
	RedirectType         *UrlRewriteRedirectType `json:"redirectType,omitempty"`
	LinkRel              *UrlRewriteLinkRel      `json:"linkRel,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UrlmanagerCreateUrlRewriteRequest UrlmanagerCreateUrlRewriteRequest

// NewUrlmanagerCreateUrlRewriteRequest instantiates a new UrlmanagerCreateUrlRewriteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUrlmanagerCreateUrlRewriteRequest() *UrlmanagerCreateUrlRewriteRequest {
	this := UrlmanagerCreateUrlRewriteRequest{}
	var redirectType UrlRewriteRedirectType = URLREWRITEREDIRECTTYPE_UNKNOWN
	this.RedirectType = &redirectType
	var linkRel UrlRewriteLinkRel = URLREWRITELINKREL_UNKNOWN
	this.LinkRel = &linkRel
	return &this
}

// NewUrlmanagerCreateUrlRewriteRequestWithDefaults instantiates a new UrlmanagerCreateUrlRewriteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUrlmanagerCreateUrlRewriteRequestWithDefaults() *UrlmanagerCreateUrlRewriteRequest {
	this := UrlmanagerCreateUrlRewriteRequest{}
	var redirectType UrlRewriteRedirectType = URLREWRITEREDIRECTTYPE_UNKNOWN
	this.RedirectType = &redirectType
	var linkRel UrlRewriteLinkRel = URLREWRITELINKREL_UNKNOWN
	this.LinkRel = &linkRel
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *UrlmanagerCreateUrlRewriteRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *UrlmanagerCreateUrlRewriteRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *UrlmanagerCreateUrlRewriteRequest) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *UrlmanagerCreateUrlRewriteRequest) SetContext(v string) {
	o.Context = &v
}

// GetRequestPath returns the RequestPath field value if set, zero value otherwise.
func (o *UrlmanagerCreateUrlRewriteRequest) GetRequestPath() string {
	if o == nil || IsNil(o.RequestPath) {
		var ret string
		return ret
	}
	return *o.RequestPath
}

// GetRequestPathOk returns a tuple with the RequestPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) GetRequestPathOk() (*string, bool) {
	if o == nil || IsNil(o.RequestPath) {
		return nil, false
	}
	return o.RequestPath, true
}

// HasRequestPath returns a boolean if a field has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) HasRequestPath() bool {
	if o != nil && !IsNil(o.RequestPath) {
		return true
	}

	return false
}

// SetRequestPath gets a reference to the given string and assigns it to the RequestPath field.
func (o *UrlmanagerCreateUrlRewriteRequest) SetRequestPath(v string) {
	o.RequestPath = &v
}

// GetTargetPath returns the TargetPath field value if set, zero value otherwise.
func (o *UrlmanagerCreateUrlRewriteRequest) GetTargetPath() string {
	if o == nil || IsNil(o.TargetPath) {
		var ret string
		return ret
	}
	return *o.TargetPath
}

// GetTargetPathOk returns a tuple with the TargetPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) GetTargetPathOk() (*string, bool) {
	if o == nil || IsNil(o.TargetPath) {
		return nil, false
	}
	return o.TargetPath, true
}

// HasTargetPath returns a boolean if a field has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) HasTargetPath() bool {
	if o != nil && !IsNil(o.TargetPath) {
		return true
	}

	return false
}

// SetTargetPath gets a reference to the given string and assigns it to the TargetPath field.
func (o *UrlmanagerCreateUrlRewriteRequest) SetTargetPath(v string) {
	o.TargetPath = &v
}

// GetRedirectType returns the RedirectType field value if set, zero value otherwise.
func (o *UrlmanagerCreateUrlRewriteRequest) GetRedirectType() UrlRewriteRedirectType {
	if o == nil || IsNil(o.RedirectType) {
		var ret UrlRewriteRedirectType
		return ret
	}
	return *o.RedirectType
}

// GetRedirectTypeOk returns a tuple with the RedirectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) GetRedirectTypeOk() (*UrlRewriteRedirectType, bool) {
	if o == nil || IsNil(o.RedirectType) {
		return nil, false
	}
	return o.RedirectType, true
}

// HasRedirectType returns a boolean if a field has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) HasRedirectType() bool {
	if o != nil && !IsNil(o.RedirectType) {
		return true
	}

	return false
}

// SetRedirectType gets a reference to the given UrlRewriteRedirectType and assigns it to the RedirectType field.
func (o *UrlmanagerCreateUrlRewriteRequest) SetRedirectType(v UrlRewriteRedirectType) {
	o.RedirectType = &v
}

// GetLinkRel returns the LinkRel field value if set, zero value otherwise.
func (o *UrlmanagerCreateUrlRewriteRequest) GetLinkRel() UrlRewriteLinkRel {
	if o == nil || IsNil(o.LinkRel) {
		var ret UrlRewriteLinkRel
		return ret
	}
	return *o.LinkRel
}

// GetLinkRelOk returns a tuple with the LinkRel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) GetLinkRelOk() (*UrlRewriteLinkRel, bool) {
	if o == nil || IsNil(o.LinkRel) {
		return nil, false
	}
	return o.LinkRel, true
}

// HasLinkRel returns a boolean if a field has been set.
func (o *UrlmanagerCreateUrlRewriteRequest) HasLinkRel() bool {
	if o != nil && !IsNil(o.LinkRel) {
		return true
	}

	return false
}

// SetLinkRel gets a reference to the given UrlRewriteLinkRel and assigns it to the LinkRel field.
func (o *UrlmanagerCreateUrlRewriteRequest) SetLinkRel(v UrlRewriteLinkRel) {
	o.LinkRel = &v
}

func (o UrlmanagerCreateUrlRewriteRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UrlmanagerCreateUrlRewriteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.RequestPath) {
		toSerialize["requestPath"] = o.RequestPath
	}
	if !IsNil(o.TargetPath) {
		toSerialize["targetPath"] = o.TargetPath
	}
	if !IsNil(o.RedirectType) {
		toSerialize["redirectType"] = o.RedirectType
	}
	if !IsNil(o.LinkRel) {
		toSerialize["linkRel"] = o.LinkRel
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UrlmanagerCreateUrlRewriteRequest) UnmarshalJSON(data []byte) (err error) {
	varUrlmanagerCreateUrlRewriteRequest := _UrlmanagerCreateUrlRewriteRequest{}

	err = json.Unmarshal(data, &varUrlmanagerCreateUrlRewriteRequest)

	if err != nil {
		return err
	}

	*o = UrlmanagerCreateUrlRewriteRequest(varUrlmanagerCreateUrlRewriteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "context")
		delete(additionalProperties, "requestPath")
		delete(additionalProperties, "targetPath")
		delete(additionalProperties, "redirectType")
		delete(additionalProperties, "linkRel")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *UrlmanagerCreateUrlRewriteRequest) GetValue() interface{} {
	if o == nil || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}

// SetValue populates the value of well-known types
func (o *UrlmanagerCreateUrlRewriteRequest) SetValue(value interface{}) {
	if o == nil || IsNil(value) {
		return
	}
	if IsNil(o.AdditionalProperties) {
		o.AdditionalProperties = map[string]interface{}{}
	}
	o.AdditionalProperties["value"] = value
	return
}

type NullableUrlmanagerCreateUrlRewriteRequest struct {
	value *UrlmanagerCreateUrlRewriteRequest
	isSet bool
}

func (v NullableUrlmanagerCreateUrlRewriteRequest) Get() *UrlmanagerCreateUrlRewriteRequest {
	return v.value
}

func (v *NullableUrlmanagerCreateUrlRewriteRequest) Set(val *UrlmanagerCreateUrlRewriteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUrlmanagerCreateUrlRewriteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUrlmanagerCreateUrlRewriteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUrlmanagerCreateUrlRewriteRequest(val *UrlmanagerCreateUrlRewriteRequest) *NullableUrlmanagerCreateUrlRewriteRequest {
	return &NullableUrlmanagerCreateUrlRewriteRequest{value: val, isSet: true}
}

func (v NullableUrlmanagerCreateUrlRewriteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUrlmanagerCreateUrlRewriteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
