/*
Url Manager Service

The URL Manager service provides a set of APIs for managing URL rewrites within your application. URL rewriting is a technique used to modify the appearance or structure of URLs while maintaining the functionality and accessibility of the underlying resources.  The URL Manager service offers various operations to create, retrieve, update, and delete URL rewrite configurations. These configurations allow you to define rules that map incoming URLs to different paths or destinations based on specific criteria. By using URL rewriting, you can enhance the user experience, improve SEO (Search Engine Optimization), and manage complex URL structures effectively.  To get started with the URL Manager service, you need to integrate the provided Proto API into your application. The API supports various programming languages and frameworks, making it easy to incorporate URL rewriting functionality into your existing codebase.  Once integrated, you can utilize the different API methods to create, manage, and query URL rewrite configurations based on your application's requirements.  Refer to the API documentation for detailed information on the request and response formats, authentication requirements, and example usage of each API method.

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package urlmanager

import (
	"encoding/json"
)

// checks if the UrlmanagerListUrlRewritesByTargetPathsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UrlmanagerListUrlRewritesByTargetPathsRequest{}

// UrlmanagerListUrlRewritesByTargetPathsRequest struct for UrlmanagerListUrlRewritesByTargetPathsRequest
type UrlmanagerListUrlRewritesByTargetPathsRequest struct {
	// Required.
	TenantId *string `json:"tenantId,omitempty"`
	// Required.
	TargetPaths []string `json:"targetPaths,omitempty"`
	// Optional.
	Context *string `json:"context,omitempty"`
	LinkRel *UrlRewriteLinkRel `json:"linkRel,omitempty"`
}

// NewUrlmanagerListUrlRewritesByTargetPathsRequest instantiates a new UrlmanagerListUrlRewritesByTargetPathsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUrlmanagerListUrlRewritesByTargetPathsRequest() *UrlmanagerListUrlRewritesByTargetPathsRequest {
	this := UrlmanagerListUrlRewritesByTargetPathsRequest{}
	var linkRel UrlRewriteLinkRel = URLREWRITELINKREL_UNKNOWN
	this.LinkRel = &linkRel
	return &this
}

// NewUrlmanagerListUrlRewritesByTargetPathsRequestWithDefaults instantiates a new UrlmanagerListUrlRewritesByTargetPathsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUrlmanagerListUrlRewritesByTargetPathsRequestWithDefaults() *UrlmanagerListUrlRewritesByTargetPathsRequest {
	this := UrlmanagerListUrlRewritesByTargetPathsRequest{}
	var linkRel UrlRewriteLinkRel = URLREWRITELINKREL_UNKNOWN
	this.LinkRel = &linkRel
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetTargetPaths returns the TargetPaths field value if set, zero value otherwise.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) GetTargetPaths() []string {
	if o == nil || IsNil(o.TargetPaths) {
		var ret []string
		return ret
	}
	return o.TargetPaths
}

// GetTargetPathsOk returns a tuple with the TargetPaths field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) GetTargetPathsOk() ([]string, bool) {
	if o == nil || IsNil(o.TargetPaths) {
		return nil, false
	}
	return o.TargetPaths, true
}

// HasTargetPaths returns a boolean if a field has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) HasTargetPaths() bool {
	if o != nil && !IsNil(o.TargetPaths) {
		return true
	}

	return false
}

// SetTargetPaths gets a reference to the given []string and assigns it to the TargetPaths field.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) SetTargetPaths(v []string) {
	o.TargetPaths = v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) SetContext(v string) {
	o.Context = &v
}

// GetLinkRel returns the LinkRel field value if set, zero value otherwise.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) GetLinkRel() UrlRewriteLinkRel {
	if o == nil || IsNil(o.LinkRel) {
		var ret UrlRewriteLinkRel
		return ret
	}
	return *o.LinkRel
}

// GetLinkRelOk returns a tuple with the LinkRel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) GetLinkRelOk() (*UrlRewriteLinkRel, bool) {
	if o == nil || IsNil(o.LinkRel) {
		return nil, false
	}
	return o.LinkRel, true
}

// HasLinkRel returns a boolean if a field has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) HasLinkRel() bool {
	if o != nil && !IsNil(o.LinkRel) {
		return true
	}

	return false
}

// SetLinkRel gets a reference to the given UrlRewriteLinkRel and assigns it to the LinkRel field.
func (o *UrlmanagerListUrlRewritesByTargetPathsRequest) SetLinkRel(v UrlRewriteLinkRel) {
	o.LinkRel = &v
}

func (o UrlmanagerListUrlRewritesByTargetPathsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UrlmanagerListUrlRewritesByTargetPathsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.TargetPaths) {
		toSerialize["targetPaths"] = o.TargetPaths
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.LinkRel) {
		toSerialize["linkRel"] = o.LinkRel
	}
	return toSerialize, nil
}

type NullableUrlmanagerListUrlRewritesByTargetPathsRequest struct {
	value *UrlmanagerListUrlRewritesByTargetPathsRequest
	isSet bool
}

func (v NullableUrlmanagerListUrlRewritesByTargetPathsRequest) Get() *UrlmanagerListUrlRewritesByTargetPathsRequest {
	return v.value
}

func (v *NullableUrlmanagerListUrlRewritesByTargetPathsRequest) Set(val *UrlmanagerListUrlRewritesByTargetPathsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUrlmanagerListUrlRewritesByTargetPathsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUrlmanagerListUrlRewritesByTargetPathsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUrlmanagerListUrlRewritesByTargetPathsRequest(val *UrlmanagerListUrlRewritesByTargetPathsRequest) *NullableUrlmanagerListUrlRewritesByTargetPathsRequest {
	return &NullableUrlmanagerListUrlRewritesByTargetPathsRequest{value: val, isSet: true}
}

func (v NullableUrlmanagerListUrlRewritesByTargetPathsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUrlmanagerListUrlRewritesByTargetPathsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


