/*
Url Manager Service

The URL Manager service provides a set of APIs for managing URL rewrites within your application. URL rewriting is a technique used to modify the appearance or structure of URLs while maintaining the functionality and accessibility of the underlying resources.  The URL Manager service offers various operations to create, retrieve, update, and delete URL rewrite configurations. These configurations allow you to define rules that map incoming URLs to different paths or destinations based on specific criteria. By using URL rewriting, you can enhance the user experience, improve SEO (Search Engine Optimization), and manage complex URL structures effectively.  To get started with the URL Manager service, you need to integrate the provided Proto API into your application. The API supports various programming languages and frameworks, making it easy to incorporate URL rewriting functionality into your existing codebase.  Once integrated, you can utilize the different API methods to create, manage, and query URL rewrite configurations based on your application's requirements.  Refer to the API documentation for detailed information on the request and response formats, authentication requirements, and example usage of each API method.

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package urlmanager

import (
	"encoding/json"
)

// checks if the UrlmanagerListUrlRewritesByTargetPathsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UrlmanagerListUrlRewritesByTargetPathsResponse{}

// UrlmanagerListUrlRewritesByTargetPathsResponse struct for UrlmanagerListUrlRewritesByTargetPathsResponse
type UrlmanagerListUrlRewritesByTargetPathsResponse struct {
	UrlRewrites []UrlmanagerUrlRewrite `json:"urlRewrites,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UrlmanagerListUrlRewritesByTargetPathsResponse UrlmanagerListUrlRewritesByTargetPathsResponse

// NewUrlmanagerListUrlRewritesByTargetPathsResponse instantiates a new UrlmanagerListUrlRewritesByTargetPathsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUrlmanagerListUrlRewritesByTargetPathsResponse() *UrlmanagerListUrlRewritesByTargetPathsResponse {
	this := UrlmanagerListUrlRewritesByTargetPathsResponse{}
	return &this
}

// NewUrlmanagerListUrlRewritesByTargetPathsResponseWithDefaults instantiates a new UrlmanagerListUrlRewritesByTargetPathsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUrlmanagerListUrlRewritesByTargetPathsResponseWithDefaults() *UrlmanagerListUrlRewritesByTargetPathsResponse {
	this := UrlmanagerListUrlRewritesByTargetPathsResponse{}
	return &this
}

// GetUrlRewrites returns the UrlRewrites field value if set, zero value otherwise.
func (o *UrlmanagerListUrlRewritesByTargetPathsResponse) GetUrlRewrites() []UrlmanagerUrlRewrite {
	if o == nil || IsNil(o.UrlRewrites) {
		var ret []UrlmanagerUrlRewrite
		return ret
	}
	return o.UrlRewrites
}

// GetUrlRewritesOk returns a tuple with the UrlRewrites field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsResponse) GetUrlRewritesOk() ([]UrlmanagerUrlRewrite, bool) {
	if o == nil || IsNil(o.UrlRewrites) {
		return nil, false
	}
	return o.UrlRewrites, true
}

// &#39;Has&#39;UrlRewrites returns a boolean if a field has been set.
func (o *UrlmanagerListUrlRewritesByTargetPathsResponse) &#39;Has&#39;UrlRewrites() bool {
	if o != nil && !IsNil(o.UrlRewrites) {
		return true
	}

	return false
}

// SetUrlRewrites gets a reference to the given []UrlmanagerUrlRewrite and assigns it to the UrlRewrites field.
func (o *UrlmanagerListUrlRewritesByTargetPathsResponse) SetUrlRewrites(v []UrlmanagerUrlRewrite) {
	o.UrlRewrites = v
}

func (o UrlmanagerListUrlRewritesByTargetPathsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UrlmanagerListUrlRewritesByTargetPathsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UrlRewrites) {
		toSerialize["urlRewrites"] = o.UrlRewrites
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UrlmanagerListUrlRewritesByTargetPathsResponse) UnmarshalJSON(data []byte) (err error) {
	varUrlmanagerListUrlRewritesByTargetPathsResponse := _UrlmanagerListUrlRewritesByTargetPathsResponse{}

	err = json.Unmarshal(data, &varUrlmanagerListUrlRewritesByTargetPathsResponse)

	if err != nil {
		return err
	}

	*o = UrlmanagerListUrlRewritesByTargetPathsResponse(varUrlmanagerListUrlRewritesByTargetPathsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "urlRewrites")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *UrlmanagerListUrlRewritesByTargetPathsResponse) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *UrlmanagerListUrlRewritesByTargetPathsResponse) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableUrlmanagerListUrlRewritesByTargetPathsResponse struct {
	value *UrlmanagerListUrlRewritesByTargetPathsResponse
	isSet bool
}

func (v NullableUrlmanagerListUrlRewritesByTargetPathsResponse) Get() *UrlmanagerListUrlRewritesByTargetPathsResponse {
	return v.value
}

func (v *NullableUrlmanagerListUrlRewritesByTargetPathsResponse) Set(val *UrlmanagerListUrlRewritesByTargetPathsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUrlmanagerListUrlRewritesByTargetPathsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUrlmanagerListUrlRewritesByTargetPathsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUrlmanagerListUrlRewritesByTargetPathsResponse(val *UrlmanagerListUrlRewritesByTargetPathsResponse) *NullableUrlmanagerListUrlRewritesByTargetPathsResponse {
	return &NullableUrlmanagerListUrlRewritesByTargetPathsResponse{value: val, isSet: true}
}

func (v NullableUrlmanagerListUrlRewritesByTargetPathsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUrlmanagerListUrlRewritesByTargetPathsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


