/*
Url Manager Service

The URL Manager service provides a set of APIs for managing URL rewrites within your application. URL rewriting is a technique used to modify the appearance or structure of URLs while maintaining the functionality and accessibility of the underlying resources.  The URL Manager service offers various operations to create, retrieve, update, and delete URL rewrite configurations. These configurations allow you to define rules that map incoming URLs to different paths or destinations based on specific criteria. By using URL rewriting, you can enhance the user experience, improve SEO (Search Engine Optimization), and manage complex URL structures effectively.  To get started with the URL Manager service, you need to integrate the provided Proto API into your application. The API supports various programming languages and frameworks, making it easy to incorporate URL rewriting functionality into your existing codebase.  Once integrated, you can utilize the different API methods to create, manage, and query URL rewrite configurations based on your application's requirements.  Refer to the API documentation for detailed information on the request and response formats, authentication requirements, and example usage of each API method.

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package urlmanager

import (
	"encoding/json"
)

// checks if the UrlmanagerGetUrlRewriteRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UrlmanagerGetUrlRewriteRequest{}

// UrlmanagerGetUrlRewriteRequest struct for UrlmanagerGetUrlRewriteRequest
type UrlmanagerGetUrlRewriteRequest struct {
	// Required.
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
	CompoundIdentifier *GetUrlRewriteRequestCompoundIdentifier `json:"compoundIdentifier,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UrlmanagerGetUrlRewriteRequest UrlmanagerGetUrlRewriteRequest

// NewUrlmanagerGetUrlRewriteRequest instantiates a new UrlmanagerGetUrlRewriteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUrlmanagerGetUrlRewriteRequest() *UrlmanagerGetUrlRewriteRequest {
	this := UrlmanagerGetUrlRewriteRequest{}
	return &this
}

// NewUrlmanagerGetUrlRewriteRequestWithDefaults instantiates a new UrlmanagerGetUrlRewriteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUrlmanagerGetUrlRewriteRequestWithDefaults() *UrlmanagerGetUrlRewriteRequest {
	this := UrlmanagerGetUrlRewriteRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *UrlmanagerGetUrlRewriteRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerGetUrlRewriteRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *UrlmanagerGetUrlRewriteRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *UrlmanagerGetUrlRewriteRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UrlmanagerGetUrlRewriteRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerGetUrlRewriteRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UrlmanagerGetUrlRewriteRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UrlmanagerGetUrlRewriteRequest) SetId(v string) {
	o.Id = &v
}

// GetCompoundIdentifier returns the CompoundIdentifier field value if set, zero value otherwise.
func (o *UrlmanagerGetUrlRewriteRequest) GetCompoundIdentifier() GetUrlRewriteRequestCompoundIdentifier {
	if o == nil || IsNil(o.CompoundIdentifier) {
		var ret GetUrlRewriteRequestCompoundIdentifier
		return ret
	}
	return *o.CompoundIdentifier
}

// GetCompoundIdentifierOk returns a tuple with the CompoundIdentifier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerGetUrlRewriteRequest) GetCompoundIdentifierOk() (*GetUrlRewriteRequestCompoundIdentifier, bool) {
	if o == nil || IsNil(o.CompoundIdentifier) {
		return nil, false
	}
	return o.CompoundIdentifier, true
}

// HasCompoundIdentifier returns a boolean if a field has been set.
func (o *UrlmanagerGetUrlRewriteRequest) HasCompoundIdentifier() bool {
	if o != nil && !IsNil(o.CompoundIdentifier) {
		return true
	}

	return false
}

// SetCompoundIdentifier gets a reference to the given GetUrlRewriteRequestCompoundIdentifier and assigns it to the CompoundIdentifier field.
func (o *UrlmanagerGetUrlRewriteRequest) SetCompoundIdentifier(v GetUrlRewriteRequestCompoundIdentifier) {
	o.CompoundIdentifier = &v
}

func (o UrlmanagerGetUrlRewriteRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UrlmanagerGetUrlRewriteRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CompoundIdentifier) {
		toSerialize["compoundIdentifier"] = o.CompoundIdentifier
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UrlmanagerGetUrlRewriteRequest) UnmarshalJSON(data []byte) (err error) {
	varUrlmanagerGetUrlRewriteRequest := _UrlmanagerGetUrlRewriteRequest{}

	err = json.Unmarshal(data, &varUrlmanagerGetUrlRewriteRequest)

	if err != nil {
		return err
	}

	*o = UrlmanagerGetUrlRewriteRequest(varUrlmanagerGetUrlRewriteRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "id")
		delete(additionalProperties, "compoundIdentifier")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *UrlmanagerGetUrlRewriteRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *UrlmanagerGetUrlRewriteRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableUrlmanagerGetUrlRewriteRequest struct {
	value *UrlmanagerGetUrlRewriteRequest
	isSet bool
}

func (v NullableUrlmanagerGetUrlRewriteRequest) Get() *UrlmanagerGetUrlRewriteRequest {
	return v.value
}

func (v *NullableUrlmanagerGetUrlRewriteRequest) Set(val *UrlmanagerGetUrlRewriteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUrlmanagerGetUrlRewriteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUrlmanagerGetUrlRewriteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUrlmanagerGetUrlRewriteRequest(val *UrlmanagerGetUrlRewriteRequest) *NullableUrlmanagerGetUrlRewriteRequest {
	return &NullableUrlmanagerGetUrlRewriteRequest{value: val, isSet: true}
}

func (v NullableUrlmanagerGetUrlRewriteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUrlmanagerGetUrlRewriteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


