/*
Url Manager Service

The URL Manager service provides a set of APIs for managing URL rewrites within your application. URL rewriting is a technique used to modify the appearance or structure of URLs while maintaining the functionality and accessibility of the underlying resources.  The URL Manager service offers various operations to create, retrieve, update, and delete URL rewrite configurations. These configurations allow you to define rules that map incoming URLs to different paths or destinations based on specific criteria. By using URL rewriting, you can enhance the user experience, improve SEO (Search Engine Optimization), and manage complex URL structures effectively.  To get started with the URL Manager service, you need to integrate the provided Proto API into your application. The API supports various programming languages and frameworks, making it easy to incorporate URL rewriting functionality into your existing codebase.  Once integrated, you can utilize the different API methods to create, manage, and query URL rewrite configurations based on your application's requirements.  Refer to the API documentation for detailed information on the request and response formats, authentication requirements, and example usage of each API method.

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package urlmanager

import (
	"encoding/json"
)

// checks if the UrlmanagerUrlRewrite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UrlmanagerUrlRewrite{}

// UrlmanagerUrlRewrite struct for UrlmanagerUrlRewrite
type UrlmanagerUrlRewrite struct {
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
	// Context field is part of the key. it's up to whoever is using the url manager to define it. e.g. locale or market or a concatenation of the two if needed.
	Context *string `json:"context,omitempty"`
	RequestPath *string `json:"requestPath,omitempty"`
	TargetPath *string `json:"targetPath,omitempty"`
	RedirectType *UrlRewriteRedirectType `json:"redirectType,omitempty"`
	LinkRel *UrlRewriteLinkRel `json:"linkRel,omitempty"`
}

// NewUrlmanagerUrlRewrite instantiates a new UrlmanagerUrlRewrite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUrlmanagerUrlRewrite() *UrlmanagerUrlRewrite {
	this := UrlmanagerUrlRewrite{}
	var redirectType UrlRewriteRedirectType = UNKNOWN
	this.RedirectType = &redirectType
	var linkRel UrlRewriteLinkRel = UNKNOWN
	this.LinkRel = &linkRel
	return &this
}

// NewUrlmanagerUrlRewriteWithDefaults instantiates a new UrlmanagerUrlRewrite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUrlmanagerUrlRewriteWithDefaults() *UrlmanagerUrlRewrite {
	this := UrlmanagerUrlRewrite{}
	var redirectType UrlRewriteRedirectType = UNKNOWN
	this.RedirectType = &redirectType
	var linkRel UrlRewriteLinkRel = UNKNOWN
	this.LinkRel = &linkRel
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *UrlmanagerUrlRewrite) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerUrlRewrite) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *UrlmanagerUrlRewrite) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *UrlmanagerUrlRewrite) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UrlmanagerUrlRewrite) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerUrlRewrite) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UrlmanagerUrlRewrite) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UrlmanagerUrlRewrite) SetId(v string) {
	o.Id = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *UrlmanagerUrlRewrite) GetContext() string {
	if o == nil || IsNil(o.Context) {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerUrlRewrite) GetContextOk() (*string, bool) {
	if o == nil || IsNil(o.Context) {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *UrlmanagerUrlRewrite) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *UrlmanagerUrlRewrite) SetContext(v string) {
	o.Context = &v
}

// GetRequestPath returns the RequestPath field value if set, zero value otherwise.
func (o *UrlmanagerUrlRewrite) GetRequestPath() string {
	if o == nil || IsNil(o.RequestPath) {
		var ret string
		return ret
	}
	return *o.RequestPath
}

// GetRequestPathOk returns a tuple with the RequestPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerUrlRewrite) GetRequestPathOk() (*string, bool) {
	if o == nil || IsNil(o.RequestPath) {
		return nil, false
	}
	return o.RequestPath, true
}

// HasRequestPath returns a boolean if a field has been set.
func (o *UrlmanagerUrlRewrite) HasRequestPath() bool {
	if o != nil && !IsNil(o.RequestPath) {
		return true
	}

	return false
}

// SetRequestPath gets a reference to the given string and assigns it to the RequestPath field.
func (o *UrlmanagerUrlRewrite) SetRequestPath(v string) {
	o.RequestPath = &v
}

// GetTargetPath returns the TargetPath field value if set, zero value otherwise.
func (o *UrlmanagerUrlRewrite) GetTargetPath() string {
	if o == nil || IsNil(o.TargetPath) {
		var ret string
		return ret
	}
	return *o.TargetPath
}

// GetTargetPathOk returns a tuple with the TargetPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerUrlRewrite) GetTargetPathOk() (*string, bool) {
	if o == nil || IsNil(o.TargetPath) {
		return nil, false
	}
	return o.TargetPath, true
}

// HasTargetPath returns a boolean if a field has been set.
func (o *UrlmanagerUrlRewrite) HasTargetPath() bool {
	if o != nil && !IsNil(o.TargetPath) {
		return true
	}

	return false
}

// SetTargetPath gets a reference to the given string and assigns it to the TargetPath field.
func (o *UrlmanagerUrlRewrite) SetTargetPath(v string) {
	o.TargetPath = &v
}

// GetRedirectType returns the RedirectType field value if set, zero value otherwise.
func (o *UrlmanagerUrlRewrite) GetRedirectType() UrlRewriteRedirectType {
	if o == nil || IsNil(o.RedirectType) {
		var ret UrlRewriteRedirectType
		return ret
	}
	return *o.RedirectType
}

// GetRedirectTypeOk returns a tuple with the RedirectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerUrlRewrite) GetRedirectTypeOk() (*UrlRewriteRedirectType, bool) {
	if o == nil || IsNil(o.RedirectType) {
		return nil, false
	}
	return o.RedirectType, true
}

// HasRedirectType returns a boolean if a field has been set.
func (o *UrlmanagerUrlRewrite) HasRedirectType() bool {
	if o != nil && !IsNil(o.RedirectType) {
		return true
	}

	return false
}

// SetRedirectType gets a reference to the given UrlRewriteRedirectType and assigns it to the RedirectType field.
func (o *UrlmanagerUrlRewrite) SetRedirectType(v UrlRewriteRedirectType) {
	o.RedirectType = &v
}

// GetLinkRel returns the LinkRel field value if set, zero value otherwise.
func (o *UrlmanagerUrlRewrite) GetLinkRel() UrlRewriteLinkRel {
	if o == nil || IsNil(o.LinkRel) {
		var ret UrlRewriteLinkRel
		return ret
	}
	return *o.LinkRel
}

// GetLinkRelOk returns a tuple with the LinkRel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UrlmanagerUrlRewrite) GetLinkRelOk() (*UrlRewriteLinkRel, bool) {
	if o == nil || IsNil(o.LinkRel) {
		return nil, false
	}
	return o.LinkRel, true
}

// HasLinkRel returns a boolean if a field has been set.
func (o *UrlmanagerUrlRewrite) HasLinkRel() bool {
	if o != nil && !IsNil(o.LinkRel) {
		return true
	}

	return false
}

// SetLinkRel gets a reference to the given UrlRewriteLinkRel and assigns it to the LinkRel field.
func (o *UrlmanagerUrlRewrite) SetLinkRel(v UrlRewriteLinkRel) {
	o.LinkRel = &v
}

func (o UrlmanagerUrlRewrite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UrlmanagerUrlRewrite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.RequestPath) {
		toSerialize["requestPath"] = o.RequestPath
	}
	if !IsNil(o.TargetPath) {
		toSerialize["targetPath"] = o.TargetPath
	}
	if !IsNil(o.RedirectType) {
		toSerialize["redirectType"] = o.RedirectType
	}
	if !IsNil(o.LinkRel) {
		toSerialize["linkRel"] = o.LinkRel
	}
	return toSerialize, nil
}

type NullableUrlmanagerUrlRewrite struct {
	value *UrlmanagerUrlRewrite
	isSet bool
}

func (v NullableUrlmanagerUrlRewrite) Get() *UrlmanagerUrlRewrite {
	return v.value
}

func (v *NullableUrlmanagerUrlRewrite) Set(val *UrlmanagerUrlRewrite) {
	v.value = val
	v.isSet = true
}

func (v NullableUrlmanagerUrlRewrite) IsSet() bool {
	return v.isSet
}

func (v *NullableUrlmanagerUrlRewrite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUrlmanagerUrlRewrite(val *UrlmanagerUrlRewrite) *NullableUrlmanagerUrlRewrite {
	return &NullableUrlmanagerUrlRewrite{value: val, isSet: true}
}

func (v NullableUrlmanagerUrlRewrite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUrlmanagerUrlRewrite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


